# 引入包

In [1]:
from numpy import *

# 加载数据集

In [2]:
# 加载数据
def loadDataSet(fileName):  # 解析文件,得到一个浮点数字类型的矩阵
    dataMat = []              # 文件的最后一个字段是类别标签
    fr = open(fileName)
    for line in fr.readlines():
        curLine = line.strip().split()
        #fltLine = map(float, curLine)    # 将每个元素转成float类型
        fltLine = list(map(float, curLine))
        dataMat.append(fltLine)
    fr.close()
    return dataMat

# 计算欧几里得距离

In [3]:
def distEclud(vecA, vecB):
    return sqrt(sum(power(vecA - vecB, 2))) # 求两个向量之间的距离

# 构建聚簇中心

In [4]:
def randCent(dataSet, k):
    n = shape(dataSet)[1]
    centroids = mat(zeros((k,n)))   # 每个质心有n个坐标值，总共要k个质心
    for j in range(n):
        minJ = min(dataSet[:,j])
        maxJ = max(dataSet[:,j])
        rangeJ = float(maxJ - minJ)
        centroids[:,j] = minJ + rangeJ * random.rand(k, 1)
    return centroids



# k-means 聚类算法

In [5]:
def kMeans(dataSet, k, distMeans =distEclud, createCent = randCent):
    m = shape(dataSet)[0]
    clusterAssment = mat(zeros((m,2)))    # 用于存放该样本属于哪类及质心距离
    # clusterAssment第一列存放该数据所属的中心点，第二列是该数据到中心点的距离
    centroids = createCent(dataSet, k)
    clusterChanged = True   # 用来判断聚类是否已经收敛
    while clusterChanged:
        clusterChanged = False;
        for i in range(m):  # 把每一个数据点划分到离它最近的中心点
            minDist = inf; minIndex = -1;
            for j in range(k):
                distJI = distMeans(centroids[j,:], dataSet[i,:])
                if distJI < minDist:
                    minDist = distJI; minIndex = j  # 如果第i个数据点到第j个中心点更近，则将i归属为j
            if clusterAssment[i,0] != minIndex: clusterChanged = True;  # 如果分配发生变化，则需要继续迭代
            clusterAssment[i,:] = minIndex,minDist**2   # 并将第i个数据点的分配情况存入字典
        print(centroids)
        for cent in range(k):   # 重新计算中心点
            ptsInClust = dataSet[nonzero(clusterAssment[:,0].A == cent)[0]]   # 去第一列等于cent的所有列
            centroids[cent,:] = mean(ptsInClust, axis = 0)  # 算出这些数据的中心点
    return centroids, clusterAssment

# 测试

In [6]:
datMat = mat(loadDataSet('dataset4.txt'))
myCentroids,clustAssing = kMeans(datMat,4)
print (myCentroids)
print (clustAssing)

[[-1.16006774  0.60735391]
 [-3.93044626  4.07485206]
 [-3.18671118 -2.23742529]
 [ 3.33746025 -3.2689781 ]]
[[ 1.7658705   1.990256  ]
 [-2.72438167  3.26469   ]
 [-3.90433975 -2.144565  ]
 [ 2.82987583 -2.37999483]]
[[ 2.611752    1.70956283]
 [-2.2408245   3.2843035 ]
 [-3.90433975 -2.144565  ]
 [ 2.5388238  -3.1877908 ]]
[[ 2.611752    1.70956283]
 [-2.2408245   3.2843035 ]
 [-3.90433975 -2.144565  ]
 [ 2.5388238  -3.1877908 ]]
[[0.         2.80277213]
 [1.         1.49064034]
 [1.         3.60094455]
 [2.         3.65912744]
 [0.         4.16200382]
 [1.         4.83311081]
 [3.         4.37371398]
 [2.         0.35059657]
 [0.         0.01641067]
 [3.         0.42649256]
 [3.         1.05215123]
 [2.         2.16043443]
 [0.         4.17515847]
 [3.         1.29671628]
 [0.         8.43067135]
 [2.         3.07371143]
 [0.         0.06673501]
 [1.         2.10791001]
 [3.         0.19241673]]
