In [3]:
import numpy as np

- 读取数据
np.genfromtxt("",delimiter=",",dtype=str)
- 查看帮助文档
print(help(numpy.genfromtxt))
- 查看结构
vector = numpy.array([1,2,3,4])
print(vector.shape)
vector.dtype
- Numpy里面的值都必须是一样的，所有的值都必须是同一种类型的
- 精度低的转换成精度高的

In [6]:
#打印出包含第二列包含25的所有列
matrix = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
second_colum_25 = (matrix[:,1] == 25) & (matrix[1,:]==25)
print(second_colum_25)
print(matrix[second_colum_25,:])

[False  True False]
[[20 25 30]]


In [7]:
# numpy的计算
matrix = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
matrix.sum(axis=1)

array([ 30,  75, 120])

In [8]:
# numpy的计算
matrix = np.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
matrix.sum(axis=0)

array([60, 75, 90])

In [15]:
# 矩阵变换
a = np.arange(15)
print(a)
a =a.reshape(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [18]:
# 随机模块
np.random.random((2,3))

array([[0.52810223, 0.73369539, 0.72207414],
       [0.96107734, 0.53353839, 0.43282634]])

In [19]:
from numpy import pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [20]:
np.sin(np.linspace(0,2*pi,100))

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [21]:
# numpy的计算
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

c = a-b
print(c)

c= c-1
print(c)

c = b**2
print(c)
print(a<35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[19 28 37 46]
[0 1 4 9]
[ True  True False False]


In [26]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])

print(A)
print("*"*20)
print(B)
print("*"*20)
print(A*B)
print("*"*20)
#矩阵相乘计算
print(A. dot(B))
print("*"*20)
#矩阵相乘计算
print(np.dot(A,B))

[[1 1]
 [0 1]]
********************
[[2 0]
 [3 4]]
********************
[[2 0]
 [0 4]]
********************
[[5 4]
 [3 4]]
********************
[[5 4]
 [3 4]]


In [28]:
C = np.arange(3)
print(C)
print(np.exp(C))
print(np.sqrt(C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [48]:
#向下取整
a = np.floor(10*np.random.random((3,4)))
print(a)
# 矩阵转换为一个向量
print(a.ravel())
a.shape = (6,2)
b = a
print(b)
print(b.T)

[[4. 3. 0. 8.]
 [3. 3. 6. 6.]
 [1. 9. 3. 1.]]
[4. 3. 0. 8. 3. 3. 6. 6. 1. 9. 3. 1.]
[[4. 3.]
 [0. 8.]
 [3. 3.]
 [6. 6.]
 [1. 9.]
 [3. 1.]]
[[4. 0. 3. 6. 1. 3.]
 [3. 8. 3. 6. 9. 1.]]


In [55]:
# 矩阵的拼接
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print("*"*20)
print(b)
print("*"*20)
#横向拼接
print(np.hstack((a,b)))
print("*"*20)
#纵向拼接
print(np.vstack((a,b)))

[[1. 8.]
 [4. 0.]]
********************
[[1. 6.]
 [5. 0.]]
********************
[[1. 8. 1. 6.]
 [4. 0. 5. 0.]]
********************
[[1. 8.]
 [4. 0.]
 [1. 6.]
 [5. 0.]]


In [57]:
#切分矩阵
a = np.floor(10*np.random.random((2,12)))
print(a)
print("*"*40)
print(np.hsplit(a,3))
print("*"*40)
print(np.hsplit(a,(3,4)))
a = np.floor(10*np.random.random((12,2)))
print("*"*40)
print(a)
np.vsplit(a,3)

[[4. 8. 3. 4. 9. 0. 4. 7. 7. 4. 8. 0.]
 [6. 5. 0. 7. 9. 0. 6. 0. 3. 8. 1. 1.]]
****************************************
[array([[4., 8., 3., 4.],
       [6., 5., 0., 7.]]), array([[9., 0., 4., 7.],
       [9., 0., 6., 0.]]), array([[7., 4., 8., 0.],
       [3., 8., 1., 1.]])]
****************************************
[array([[4., 8., 3.],
       [6., 5., 0.]]), array([[4.],
       [7.]]), array([[9., 0., 4., 7., 7., 4., 8., 0.],
       [9., 0., 6., 0., 3., 8., 1., 1.]])]
****************************************
[[0. 5.]
 [5. 1.]
 [5. 0.]
 [0. 5.]
 [2. 5.]
 [7. 8.]
 [1. 2.]
 [4. 4.]
 [8. 4.]
 [4. 6.]
 [4. 4.]
 [1. 0.]]


[array([[0., 5.],
        [5., 1.],
        [5., 0.],
        [0., 5.]]), array([[2., 5.],
        [7., 8.],
        [1., 2.],
        [4., 4.]]), array([[8., 4.],
        [4., 6.],
        [4., 4.],
        [1., 0.]])]

In [58]:
# 赋值问题
a = np.arange(12)
b = a
print(b is a )
b.shape = 3,4
print(id(a))
print(id(b))

True
1527973440928
1527973440928


In [60]:
# 浅赋值
c = a.view()
print(c is a)
c.shape = 2,6
print(c)
c[0,4]=1234
print(a)
print(id(a))
print(id(c))

False
[[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
1527973440928
1527973473296


In [61]:
d = a.copy()
d is a 
d[0,0] = 9999
print(d)
print(a)

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [63]:
#排序
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
ind = data.argmax(axis=0)
print(ind)
data_max = data[ind,range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [65]:
# 矩阵的扩展
a = np.arange(0,40,10)
print(a)
b = np.tile(a,(2,2))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [69]:
a = np.array([[4,3,5],[1,2,1]])
print(a)
print("*"*20)
b = np.sort(a,axis=1)
print(b)

a.sort(axis=1)
print("*"*20)
print(a)
a = np.array([4,3,1,2])
#求索引
j = np.argsort(a)
print("*"*20)
print(j)
print("*"*20)
print(a[j])

[[4 3 5]
 [1 2 1]]
********************
[[3 4 5]
 [1 1 2]]
********************
[[3 4 5]
 [1 1 2]]
********************
[2 3 1 0]
********************
[1 2 3 4]
